apiVersion: v1
kind: Service
metadata:
  labels:
    mlops.service: mlflow-tracking
  name: mlflow-tracking
spec:
  ports:
    - name: 'mlflow-tracking-server'
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  selector:
    mlops.service: mlflow-tracking