apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-db-pv
  labels:
    mlops.service: mlflow-db-pv
spec:
  storageClassName: manual
  claimRef:
    namespace: default
    name: mlflow-db-pvc
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/mlflow_db/data