apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: minio-init
        image: minio/mc
        command: ["/bin/sh", "-c"]
        args: 
        - until (/usr/bin/mc alias set minio http://minio:9000 'admin' 'sample_key') do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc mb minio/mlflow;
          /usr/bin/mc mb minio/sf-listing;
          exit 0;
      restartPolicy: Never
