apiVersion: v1
kind: Service
metadata:
  labels:
    mlops.service: minio
  name: minio
spec:
  selector:
    mlops.service: minio
  type: LoadBalancer
  ports:
  - name: "minio-ui"
    port: 9000
    targetPort: 9000
  - name: "9001"
    port: 9001
    targetPort: 9001
status:
  loadBalancer: {}  
