apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    mlops.service: minio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/minio/data