apiVersion: v1
kind: Service
metadata:
  labels:
    mlops.service: mlflow-db
  name: mlflow-db
spec:
  selector:
    mlops.service: mlflow-db
  type: ClusterIP
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
status:
  loadBalancer: {}  
