apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
  labels:
    mlops.service: notebooks-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv/notebooks/data