apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZy5ubC1hbXMuc2N3LmNsb3VkIjogewoJCQkiYXV0aCI6ICJibTlzYjJkcGJqbzVOR1EzWlRrd05DMWlOV1l6TFRRM1pHWXRPV0kwWWkwek5XSTJNRE15T0RCaU5qaz0iCgkJfQoJfQp9
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson


# kubectl create secret generic regcred --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson