apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mlops.service: spark-worker
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      mlops.service: spark-worker
  strategy: {}
  template:
    metadata:
      labels:
        mlops.service: spark-worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - env:
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_MASTER
              value: spark://spark-master:7077
            - name: SPARK_MODE
              value: worker
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: 1G         
          image: rg.nl-ams.scw.cloud/mlops-datapebbles/spark-worker:3.3
          ports:
            - containerPort: 8081
          name: spark-worker
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
